#!/usr/bin/env node

//
// Launcher for PhotoStructure for Servers
//

const { argv } = require("process");
const validCommands = ["main", "web", "sync", "sync-file", "info", "logtail"];
const cmd = argv.find(ea => validCommands.includes(ea)) || "main";
require("./app/" + cmd);
