-- PhotoStructure Database Schema
-- Generated by library/db/DbSchemaValid.js
-- Tables
CREATE TABLE "Asset" (
  id INTEGER NOT NULL PRIMARY KEY,
  shown INTEGER NOT NULL DEFAULT 0,
  hidden INTEGER NOT NULL DEFAULT 0,
  capturedAtLocal INTEGER NOT NULL,
  mimetype TEXT NOT NULL,
  rating INTEGER,
  durationMs INTEGER,
  flags INTEGER,
  deletedAt INTEGER,
  excludedAt INTEGER,
  createdAt INTEGER NOT NULL,
  updatedAt INTEGER NOT NULL,
  updateCount INTEGER NOT NULL DEFAULT 0
) STRICT;

CREATE TABLE "AssetFile" (
  id INTEGER NOT NULL PRIMARY KEY,
  dirUriId INTEGER NOT NULL REFERENCES DirUri (id),
  basename TEXT NOT NULL,
  assetId INTEGER REFERENCES "Asset" (id),
  isPrimary INTEGER NOT NULL DEFAULT 0,
  mtime INTEGER NOT NULL,
  fileSize INTEGER NOT NULL,
  mimetype TEXT NOT NULL,
  width INTEGER NOT NULL,
  height INTEGER NOT NULL,
  rotation INTEGER,
  durationMs INTEGER,
  cameraId TEXT,
  lensId TEXT,
  imageDataHash TEXT,
  imageId TEXT,
  metadataDate INTEGER,
  sha TEXT NOT NULL,
  capturedAtLocal INTEGER NOT NULL,
  capturedAtPrecisionMs INTEGER,
  capturedAtZone TEXT,
  capturedAtSrc TEXT,
  make TEXT,
  model TEXT,
  rating INTEGER,
  aperture REAL,
  focalLength TEXT,
  fps REAL,
  geohash INTEGER,
  iso INTEGER,
  shutterSpeed TEXT,
  monochrome INTEGER,
  pHash TEXT,
  rHash TEXT,
  wHash TEXT,
  pHash0 TEXT,
  rHash0 TEXT,
  wHash0 TEXT,
  flags INTEGER,
  createdAt INTEGER NOT NULL,
  updatedAt INTEGER NOT NULL,
  updateCount INTEGER NOT NULL DEFAULT 0,
  lastVisitedGeneration INTEGER
) STRICT;

CREATE TABLE "AssetRevision" (
  id INTEGER NOT NULL PRIMARY KEY,
  assetId INTEGER NOT NULL,
  createdAt INTEGER NOT NULL,
  field TEXT NOT NULL,
  op TEXT,
  _priorValueJson TEXT,
  _newValueJson TEXT,
  FOREIGN KEY (assetId) REFERENCES Asset (id)
) STRICT;

CREATE TABLE "AssetTag" (
  assetId INTEGER NOT NULL,
  tagId INTEGER NOT NULL,
  FOREIGN KEY (assetId) REFERENCES Asset (id) ON DELETE CASCADE,
  FOREIGN KEY (tagId) REFERENCES Tag (id) ON DELETE CASCADE
) STRICT;

CREATE TABLE DirUri (
  id INTEGER NOT NULL PRIMARY KEY,
  uri TEXT NOT NULL
) STRICT;

CREATE TABLE "Example" (
  id INTEGER NOT NULL PRIMARY KEY,
  name TEXT NOT NULL,
  isExample INTEGER,
  createdAt INTEGER NOT NULL,
  updatedAt INTEGER NOT NULL
) STRICT;

CREATE TABLE Heartbeat (
  id INTEGER NOT NULL PRIMARY KEY,
  name TEXT NOT NULL,
  createdAt INTEGER NOT NULL,
  updatedAt INTEGER NOT NULL
) STRICT;

CREATE TABLE "Operation" (
  id INTEGER NOT NULL PRIMARY KEY,
  name TEXT NOT NULL,
  value TEXT,
  createdAt INTEGER NOT NULL,
  updatedAt INTEGER NOT NULL,
  completedAt INTEGER
) STRICT;

CREATE TABLE "Progress" (
  id INTEGER NOT NULL PRIMARY KEY,
  uri TEXT NOT NULL,
  hostname TEXT NOT NULL,
  pid INTEGER NOT NULL,
  volume TEXT NOT NULL,
  state TEXT,
  hed TEXT,
  dekJSON TEXT,
  completePct REAL,
  incompletePct REAL,
  scanningPct REAL,
  createdAt INTEGER NOT NULL,
  updatedAt INTEGER NOT NULL,
  completedAt INTEGER
) STRICT;

CREATE TABLE "ProgressMeta" (
  id INTEGER NOT NULL PRIMARY KEY,
  progressId INTEGER NOT NULL,
  name TEXT NOT NULL,
  value TEXT NOT NULL,
  createdAt INTEGER NOT NULL,
  updatedAt INTEGER NOT NULL,
  FOREIGN KEY (progressId) REFERENCES Progress (id)
) STRICT;

CREATE TABLE RejectedFile (
  id INTEGER NOT NULL PRIMARY KEY,
  dirUriId INTEGER NOT NULL REFERENCES DirUri (id),
  basename TEXT NOT NULL,
  mtime INTEGER NOT NULL,
  fileSize INTEGER NOT NULL,
  why TEXT NOT NULL,
  updatedAt INTEGER NOT NULL
) STRICT;

CREATE TABLE "Session" (
  sid TEXT NOT NULL PRIMARY KEY,
  expired INTEGER NOT NULL,
  sess TEXT NOT NULL
) STRICT;

CREATE TABLE "ShaBlocklist" (sha TEXT NOT NULL PRIMARY KEY) STRICT;

CREATE TABLE "Tag" (
  id INTEGER NOT NULL PRIMARY KEY,
  parentId INTEGER,
  _path TEXT NOT NULL COLLATE NOCASE,
  ordinal INTEGER,
  createdAt INTEGER NOT NULL,
  updatedAt INTEGER NOT NULL,
  assetCount INTEGER DEFAULT 0,
  _displayName TEXT,
  description TEXT,
  releasedAt INTEGER,
  FOREIGN KEY (parentId) REFERENCES Tag (id)
) STRICT;

CREATE TABLE TagHierarchy (
  tagId INTEGER NOT NULL,
  descendantId INTEGER NOT NULL,
  depth INTEGER NOT NULL,
  PRIMARY KEY (tagId, descendantId),
  FOREIGN KEY (tagId) REFERENCES Tag (id) ON DELETE CASCADE,
  FOREIGN KEY (descendantId) REFERENCES Tag (id) ON DELETE CASCADE
) STRICT;

CREATE TABLE Volume (
  id INTEGER PRIMARY KEY,
  authority TEXT NOT NULL,
  mountPoint TEXT NOT NULL,
  lastSeenAt INTEGER NOT NULL
) STRICT;

CREATE TABLE "migrations" (
  id INTEGER NOT NULL PRIMARY KEY,
  name TEXT NOT NULL,
  migration_time INTEGER NOT NULL
) STRICT;

CREATE VIRTUAL TABLE tag_fts USING fts5 (
  root,
  path,
  content = '',
  contentless_delete = 1,
  tokenize = 'unicode61'
);

-- Indices
CREATE INDEX AssetFile_assetId_idx ON AssetFile (assetId, flags);

CREATE INDEX AssetFile_imageDataHash_idx ON AssetFile (imageDataHash)
WHERE
  imageDataHash IS NOT NULL;

CREATE UNIQUE INDEX AssetFile_primary_udx ON AssetFile (assetId, isPrimary)
WHERE
  assetId IS NOT NULL
  AND isPrimary = 1;

CREATE INDEX AssetFile_sha_idx ON AssetFile (sha);

CREATE UNIQUE INDEX AssetFile_uri_udx ON AssetFile (dirUriId, basename);

CREATE INDEX AssetTag_assetId_tagId_idx ON AssetTag (assetId, tagId);

CREATE UNIQUE INDEX AssetTag_tagId_assetId_udx ON AssetTag (tagId, assetId);

CREATE INDEX Asset_capturedAtLocal_idx ON Asset (capturedAtLocal)
WHERE
  shown = 1
  AND hidden = 0
  AND excludedAt IS NULL
  AND deletedAt IS NULL;

CREATE INDEX Asset_captured_at_idx ON Asset (id, capturedAtLocal);

CREATE INDEX Asset_not_hidden_idx ON Asset (id)
WHERE
  hidden = 0
  AND excludedAt IS NULL
  AND deletedAt IS NULL;

CREATE INDEX Asset_previews_idx ON Asset (id)
WHERE
  (flags & 8) != 0;

CREATE INDEX Asset_reaggregate_idx ON Asset (id)
WHERE
  (flags & 1) != 0;

CREATE INDEX Asset_sort_idx ON Asset (id)
WHERE
  (flags & 2) != 0;

CREATE INDEX Asset_tag_idx ON Asset (id)
WHERE
  (flags & 4) != 0;

CREATE UNIQUE INDEX DirUri_uri_udx ON DirUri (uri);

CREATE UNIQUE INDEX RejectedFile_udx ON RejectedFile (dirUriId, basename);

CREATE INDEX TagHierarchy_descendantId_depth_idx ON TagHierarchy (descendantId, depth);

CREATE INDEX TagHierarchy_tagId_depth_idx ON TagHierarchy (tagId, depth);

CREATE INDEX Tag_parentId_idx ON Tag (parentId);

CREATE UNIQUE INDEX Tag_path_udx ON Tag (_path COLLATE NOCASE);

CREATE UNIQUE INDEX Volume_authority_mountpoint_udx ON Volume (authority, mountPoint);

CREATE UNIQUE INDEX example_name_udx ON Example (name);

CREATE UNIQUE INDEX heartbeat_name_udx ON Heartbeat (name);

CREATE INDEX idx_assetfile_generation ON AssetFile (lastVisitedGeneration);

CREATE UNIQUE INDEX progressmeta_fk_name_udx ON ProgressMeta (progressId, name);
